### ISSUE TITLE
Getting error on updating any attribute on category with multistore

### ISSUE THREAD

**Issue by savla-jigs** [diglin/ricento#4]
Getting this error
```Attribute "Available Product Listing Sort By" is required.```

check below image for error details when I was trying to update position according to store
![image](https://cloud.githubusercontent.com/assets/4929412/12189896/42452172-b5e8-11e5-9a94-c08224665ef9.png)

**Comment by diglin** [comment]
Hi, why do you think it's related to this ricardo extension ?

**Comment by savla-jigs** [comment]
Because previously, it was working fine. But, after installing your module its showing me error.

**Comment by diglin** [comment]
If you disable the extension, what happens ? On my side I cannot reproduce your issue with the extension.
However I got this issue once on an other installation where the ricento extension was not installed. It was due to something else, I don't remember what. Probably reindexing the catalog helps.

**Comment by savla-jigs** [comment]
Well, if I disable the extension through "/app/etc/modules/Diglin_Ricento.xml" and navigate to category than I getting another error.

```
Fatal error: Class 'Mage_Diglin_Ricento_Block_Adminhtml_Products_Category_Form_Renderer_Mapping' not found in /home/www/lib/Varien/Data/Form/Abstract.php on line 146
```

**Comment by diglin** [comment]
ah yes, you cannot disable it like that, you will have to remove it completely. Forget my idea to disable it. I don't know how to help further as it is specific to your installation.
